version: "3"
services:
  #=================================
  # DATABASE SERVICES ENVIRONMENT
  #=================================
  database:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      test: env | grep HOME
      retries: 5
      start_period: 60s
      interval: 30s
      timeout: 120s
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=restuwahyu13
      - POSTGRES_PASSWORD=restuwahyu13
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgres/data
    networks:
      - go_networks
  #=================================
  # VOLUMES PERSISTENT DATA
  #=================================
volumes:
  database:
    #=================================
    # NETWORKS SHARING GROUP
    #=================================
networks:
  go_networks:
